/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import com.google.gson.Gson;
import java.sql.*;
import dao.ConnectionProvider;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.glxn.qrgen.core.image.ImageType;
import net.glxn.qrgen.javase.QRCode;
import utility.BDUtility;

/**
 *
 * @author spand
 */
public class GenerateQR extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GenerateQR.class.getName());

    /**
     * Creates new form GenerateQR
     */
    public GenerateQR() {
        initComponents();
        BDUtility.setImage(this, "images/abc1.jpg", 1163, 600);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, Color.BLACK));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUserRegistration = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        labelImage = new javax.swing.JLabel();
        saveQRButton = new javax.swing.JButton();
        saveQRAtButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1163, 600));
        setMinimumSize(new java.awt.Dimension(1163, 600));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        labelUserRegistration.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelUserRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUserRegistration.setText("Generate QR Code");

        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitButton.setText("X");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Gender", "Email", "Contact", "Address", "State", "City", "Registration ID"
            }
        ));
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userTable);

        jInternalFrame1.setVisible(true);

        labelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        saveQRButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        saveQRButton.setText("SAVE QR");
        saveQRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveQRButtonActionPerformed(evt);
            }
        });

        saveQRAtButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        saveQRAtButton.setText("SAVE QR AT");
        saveQRAtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveQRAtButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelUserRegistration)
                .addGap(435, 435, 435)
                .addComponent(exitButton)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveQRButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(saveQRAtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(labelUserRegistration)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveQRButton)
                            .addComponent(saveQRAtButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    String email=null;
    ByteArrayOutputStream out=null;
    
    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked

        int index=userTable.getSelectedRow();
        TableModel model=userTable.getModel();
        
        String id=model.getValueAt(index, 0).toString();
        String name=model.getValueAt(index, 1).toString();
        email=model.getValueAt(index, 3).toString();
        String registrationId=model.getValueAt(index, 8).toString();
        
        Map<String, String> data=new HashMap<>();
        data.put("id", id);
        data.put("name", name);
        data.put("email", email);
        data.put("registrationId", registrationId);
        
        Gson gson=new Gson();
        String jsonData=gson.toJson(data);
        
        out=QRCode.from(jsonData).withSize(322, 286).to(ImageType.PNG).stream();
        
        try
        {
            byte imageData[]=out.toByteArray();
            ImageIcon icon=new ImageIcon(imageData);
            labelImage.setIcon(icon);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Something went wrong", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_userTableMouseClicked

    private void labelImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImageMouseClicked

    }//GEN-LAST:event_labelImageMouseClicked

    private void saveQRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveQRButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            if(out==null)
            {
                JOptionPane.showMessageDialog(this, "No QR is generated !");
                return;
            }
            
            String defaultDirectory=BDUtility.getPath("qrCodes");
            File directory=new File(defaultDirectory);
            
            if(!directory.exists())
            {
                directory.mkdirs();
            }
            
            File defaultFile=new File(directory, email+".jpg");
            
            try
            {
                java.nio.file.Files.write(defaultFile.toPath(), out.toByteArray());
                JOptionPane.showMessageDialog(null, "QR code saved successfully");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error saving QR code.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Something went wrong");
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveQRButtonActionPerformed

    private void saveQRAtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveQRAtButtonActionPerformed

        try
        {
            if(out==null)
            {
                JOptionPane.showMessageDialog(null, "No QR code generated");
                return;
            }
            
            JFileChooser fileChooser=new JFileChooser();
            fileChooser.setDialogTitle("Save QR code at");
            fileChooser.setSelectedFile(new File(email+".png"));
            int userSelection=fileChooser.showSaveDialog(this);
            
            if(userSelection==JFileChooser.APPROVE_OPTION)
            {
                File fileToSave=fileChooser.getSelectedFile();
                
                try
                {
                    java.nio.file.Files.write(fileToSave.toPath(), out.toByteArray());
                    JOptionPane.showMessageDialog(this, "QR code saved successfully");
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Something went wrong, Error in saving QR code", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveQRAtButtonActionPerformed

    private void fetchUser()
    {
        DefaultTableModel model=(DefaultTableModel) userTable.getModel();
        model.setRowCount(0);
        
        try
        {
            Connection c=ConnectionProvider.getConn();
            Statement statement=c.createStatement();
            ResultSet resultSet=statement.executeQuery("SELECT * FROM userdetails");
            while(resultSet.next())
            {
                model.addRow(new Object[]{
                    resultSet.getString("id"),
                    resultSet.getString("name"),
                    resultSet.getString("gender"),
                    resultSet.getString("email"),
                    resultSet.getString("contact"),
                    resultSet.getString("address"),
                    resultSet.getString("state"),
                    resultSet.getString("city"),
                    resultSet.getString("regid")
                });
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Something went wrong");
        }
    }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        fetchUser();
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GenerateQR().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelUserRegistration;
    private javax.swing.JButton saveQRAtButton;
    private javax.swing.JButton saveQRButton;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
