/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.sql.*;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import dao.ConnectionProvider;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import utility.BDUtility;

/**
 *
 * @author spand
 */
public class MarkAttendance extends javax.swing.JFrame implements Runnable, ThreadFactory {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MarkAttendance.class.getName());

    /**
     * Creates new form MarkAttendance
     */
    
    private WebcamPanel panel=null;
    private Webcam webcam=null;
    private ExecutorService executor=Executors.newSingleThreadExecutor(this);
    private volatile boolean running=true;
    Map<String, String> resultMap=new HashMap<String, String>();
    
    public MarkAttendance() {
        initComponents();
        BDUtility.setImage(this, "images/abc1.jpg", 1370, 780);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, Color.BLACK));
        
        Timer timer=new Timer(1, e->updateTime());
        timer.start();
        
        initWebcam();
    }
    
    private void updateTime()
    {
        SimpleDateFormat simpleDateFormat=new SimpleDateFormat("YYYY-MM-dd     HH:mm:ss:SSS");
        labelCurrentTime.setText(simpleDateFormat.format(new Date()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUserRegistration = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        labelImage = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();
        labelCurrentTime = new javax.swing.JLabel();
        labelCheckInCheckOut = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelWebcamPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1370, 780));
        setUndecorated(true);

        labelUserRegistration.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelUserRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUserRegistration.setText("Mark Attendance");

        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exitButton.setText("X");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        labelImage.setBackground(new java.awt.Color(255, 255, 255));
        labelImage.setMaximumSize(new java.awt.Dimension(300, 300));
        labelImage.setMinimumSize(new java.awt.Dimension(300, 300));

        labelDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelDate.setText("Date");

        labelTime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTime.setText("Time");

        labelCurrentTime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCurrentTime.setText("Time");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelWebcamPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(labelUserRegistration)
                .addGap(522, 522, 522)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelWebcamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(labelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(labelCurrentTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelCheckInCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(1027, Short.MAX_VALUE)
                    .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(118, 118, 118)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(labelUserRegistration))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDate)
                    .addComponent(labelTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelCurrentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(labelCheckInCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelWebcamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(546, Short.MAX_VALUE)
                    .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(193, 193, 193)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        running=false;
        stopWebcam();
        
        if(executor!=null && !executor.isShutdown())
        {
            executor.shutdown();
        }
        
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MarkAttendance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCheckInCheckOut;
    private javax.swing.JLabel labelCurrentTime;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelTime;
    private javax.swing.JLabel labelUserRegistration;
    private javax.swing.JPanel labelWebcamPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run()
    {
        do
        {
            try
            {
                Thread.sleep(100);
            }
            catch(InterruptedException e)
            {
                e.printStackTrace();
            }
            
            try
            {
                Result result=null;
                BufferedImage image=null;
                
                if(webcam.isOpen() && webcam!=null)
                {
                    if((image=webcam.getImage())==null)
                    {
                        continue;
                    }
                }
                
                LuminanceSource source=new BufferedImageLuminanceSource(image);
                BinaryBitmap bitmap=new BinaryBitmap(new HybridBinarizer(source));
                
                try
                {
                    result=new MultiFormatReader().decode(bitmap);
                }
                catch(Exception E)
                {
                    
                }
                
                if(result!=null)
                {
                    String jsonString=result.getText();
                    Gson gson=new Gson();
                    java.lang.reflect.Type type=new TypeToken<Map<String, String>>(){}.getType();
                    resultMap=gson.fromJson(jsonString, type);
                    
                    String finalPath=BDUtility.getPath("images")+resultMap.get("email")+".jpg";
                    CircularImageFrame(finalPath);
                    
                    Thread.sleep(5000);
                }
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }while(running);
    }

    @Override
    public Thread newThread(Runnable r)
    {
        Thread t=new Thread(r, "My Thread");
        t.setDaemon(true);
        return t;
    }
    
    private void stopWebcam()
    {
        if(webcam!=null || webcam.isOpen())
        {
            webcam.close();
        }
    }
    
    private void initWebcam()
    {
        webcam=Webcam.getDefault();
        
        if(webcam!=null)
        {
            Dimension resolutions[]=webcam.getViewSizes();
            Dimension maxResolution=resolutions[resolutions.length-1];
        
            if(webcam.isOpen())
            {
                webcam.close();
            }
        
            webcam.setViewSize(maxResolution);
            webcam.open();
            
            panel=new WebcamPanel(webcam);
            panel.setPreferredSize(maxResolution);
            panel.setFPSDisplayed(true);
            
            labelWebcamPanel.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 689, 518));
            executor.execute(this);
            executor.shutdown();
        }
        else
        {
            System.out.println("Webcam not detected.");
        }
        
    }

    private BufferedImage imagee=null;
    private void CircularImageFrame(String imagePath)
    {
        try
        {
            Connection c=ConnectionProvider.getConn();
            Statement statement=c.createStatement();
            ResultSet resultSet=statement.executeQuery("SELECT * FROM userdetails WHERE email='"+resultMap.get("email")+"';");
            
            if(!resultSet.next())
            {
                showPopUpForCertainDuration("User is not Registered or Deleted", "Invalid QR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            imagee=null;
            File imageFile=new File(imagePath);
            
            if(imageFile.exists())
            {
                try
                {
                    imagee=ImageIO.read(imageFile);
                    imagee=createCircularImage(imagee);
                    ImageIcon icon=new ImageIcon(imagee);
                    labelImage.setIcon(icon);
                }
                catch(Exception e)
                {
                    e.printStackTrace();
                }
            }
            else
            {
                BufferedImage imageee=new BufferedImage(300, 300, BufferedImage.TYPE_INT_ARGB);
                Graphics2D g2d=imageee.createGraphics();
                
                g2d.setColor(Color.BLACK);
                g2d.fillOval(25, 25, 250, 250);
                
                g2d.setFont(new Font("", Font.BOLD, 250));
                g2d.setColor(Color.WHITE);
                g2d.drawString(String.valueOf(resultMap.get("name").charAt(0)).toUpperCase(), 75, 225);
                
                ImageIcon imageIconn=new ImageIcon(imageee);
                labelImage.setIcon(imageIconn);
                this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.pack();
                this.setLocationRelativeTo(null);
                this.setVisible(true);
            }
            
            labelName.setHorizontalAlignment(JLabel.CENTER);
            labelName.setText(resultMap.get("name"));
            
            if(!checkInCheckOut())
            {
                return;
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    private void showPopUpForCertainDuration(String popUpMessage, String popUpHeader, Integer iconId) throws HeadlessException
    {
        final JOptionPane optionPane=new JOptionPane(popUpMessage, iconId);
        final JDialog dialog=optionPane.createDialog(popUpHeader);
        Timer timer=new Timer(5000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                dialog.dispose();
                clearUserDetails();
            }
        });
        
        timer.setRepeats(false);
        timer.start();
        dialog.setVisible(true);
    }
    
    private void clearUserDetails()
    {
        labelCheckInCheckOut.setText("");
        labelCheckInCheckOut.setBackground(null);
        labelCheckInCheckOut.setForeground(null);
        labelCheckInCheckOut.setOpaque(false);
        labelName.setText("");
        labelImage.setIcon(null);
    }

    private BufferedImage createCircularImage(BufferedImage image)
    {
        int diameter=285;
        BufferedImage resizedImage=new BufferedImage(diameter, diameter, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2=resizedImage.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(image, 0, 0, diameter, diameter, null);
        g2.dispose();
        
        BufferedImage circularImage=new BufferedImage(diameter, diameter, BufferedImage.TYPE_INT_ARGB);
        g2=circularImage.createGraphics();
        Ellipse2D.Double circle=new Ellipse2D.Double(0, 0, diameter, diameter);
        g2.setClip(circle);
        g2.drawImage(resizedImage, 0, 0, null);
        g2.dispose();
        return circularImage;
    }

    private boolean checkInCheckOut() throws HeadlessException, SQLException
    {
        String popUpHeader=null;
        String popUpMessage=null;
        Color color=null;
        
        Connection c=ConnectionProvider.getConn();
        Statement statement=c.createStatement();
        
        LocalDate currentDate=LocalDate.now();
        DateTimeFormatter dateFormatter=DateTimeFormatter.ofPattern("yyyy-MM-dd");
        
        LocalDateTime currentDateTime=LocalDateTime.now();
        DateTimeFormatter dateTimeFormatter=DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        
        ResultSet resultSet=statement.executeQuery("SELECT * FROM userattendance WHERE date='"+currentDate.format(dateFormatter)+"' AND userid="+Integer.valueOf(resultMap.get("id"))+";");
        
        Connection connection=ConnectionProvider.getConn();
        
        if(resultSet.next())
        {
            String checkOutDateTime=resultSet.getString("checkout");
            
            if(checkOutDateTime!=null)
            {
                popUpMessage="Already CheckOut for the day";
                popUpHeader="Invalid Checkout";
                showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.ERROR_MESSAGE);
                return false;
            }
            
            String checkInDateTime=resultSet.getString("checkin");
            LocalDateTime checkInLocalDateTime=LocalDateTime.parse(checkInDateTime, dateTimeFormatter);
            Duration duration=Duration.between(checkInLocalDateTime, currentDateTime);
            
            long hours=duration.toHours();
            long minutes=duration.minusHours(hours).toMinutes();
            long seconds=duration.minusHours(hours).minusMinutes(minutes).getSeconds();
            
            if(!(hours>0 || (hours==0 && minutes>=5)))
            {
                long remainingMinutes=4-minutes;
                long remainingSeconds=60-seconds;
                
                popUpMessage=String.format("Your work duration is less than 5 minutes\nYou can check out after %d minutes and %d seconds", remainingMinutes, remainingSeconds);
                popUpHeader="Duration Warning";
                
                showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.WARNING_MESSAGE);
                return false;
            }
            
            String updateQuery="UPDATE userattendance SET checkout=?, workduration=? WHERE date=? AND userid=?";
            PreparedStatement preparedStatement=connection.prepareStatement(updateQuery);
            preparedStatement.setString(1, currentDateTime.format(dateTimeFormatter));
            preparedStatement.setString(2, hours+" Hours and "+minutes+" Minutes");
            preparedStatement.setString(3, currentDate.format(dateFormatter));
            preparedStatement.setString(4, resultMap.get("id"));
            
            preparedStatement.executeUpdate();
            popUpHeader="CheckOut";
            popUpMessage="Checked Out at "+currentDateTime.format(dateTimeFormatter)+"\nWork Duration "+hours+" Hours and "+minutes+" Minutes";
            color=Color.RED;
        }
        else
        {
//            CheckIn
            String insertQuery="INSERT INTO userattendance (userid, date, checkin) VALUES (?, ?, ?)";
            PreparedStatement preparedStatement=connection.prepareStatement(insertQuery);
            preparedStatement.setString(1, resultMap.get("id"));
            preparedStatement.setString(2, currentDate.format(dateFormatter));
            preparedStatement.setString(3, currentDateTime.format(dateTimeFormatter));
            preparedStatement.executeUpdate();
            popUpHeader="CheckIn";
            popUpMessage="Check In at "+currentDateTime.format(dateTimeFormatter);
            color=Color.GREEN;
            
        }
        
        labelCheckInCheckOut.setHorizontalAlignment(JLabel.CENTER);
        labelCheckInCheckOut.setText(popUpHeader);
        labelCheckInCheckOut.setForeground(color);
        labelCheckInCheckOut.setBackground(Color.DARK_GRAY);
        labelCheckInCheckOut.setOpaque(true);
        showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.INFORMATION_MESSAGE);
        return Boolean.TRUE;
    }
    
    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
        if(imagee!=null)
        {
            g.drawImage(imagee, 0, 0, null);
        }
    }
}
