/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.sql.*;
import dao.ConnectionProvider;
import java.awt.Color;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utility.BDUtility;

/**
 *
 * @author spand
 */
public class ViewAttendance extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewAttendance.class.getName());

    /**
     * Creates new form ViewAttendance
     */
    public ViewAttendance() {
        initComponents();
        BDUtility.setImage(this, "images/abc1.jpg", 1100, 500);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, Color.BLACK));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        labelUserRegistration = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        dateChooserFrom = new com.toedter.calendar.JDateChooser();
        dateChooserTo = new com.toedter.calendar.JDateChooser();
        textSearch = new javax.swing.JTextField();
        labelFrom = new javax.swing.JLabel();
        labelTo = new javax.swing.JLabel();
        labelSearch = new javax.swing.JLabel();
        labelPresent = new javax.swing.JLabel();
        labelAbsent = new javax.swing.JLabel();
        presentLabel = new javax.swing.JLabel();
        absentLabel = new javax.swing.JLabel();
        checkBoxContact = new javax.swing.JCheckBox();
        checkBoxAddress = new javax.swing.JCheckBox();
        checkBoxState = new javax.swing.JCheckBox();
        checkBoxCity = new javax.swing.JCheckBox();
        checkBoxRegID = new javax.swing.JCheckBox();
        resetFiltersButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 500));
        setMinimumSize(new java.awt.Dimension(1100, 500));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exitButton.setText("X");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        labelUserRegistration.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelUserRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUserRegistration.setText("Attendance Track");

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(userTable);

        dateChooserFrom.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateChooserFromPropertyChange(evt);
            }
        });

        dateChooserTo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateChooserToPropertyChange(evt);
            }
        });

        textSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSearchActionPerformed(evt);
            }
        });
        textSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textSearchKeyReleased(evt);
            }
        });

        labelFrom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelFrom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelFrom.setText("On/From");

        labelTo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTo.setText("To");

        labelSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelSearch.setText("Search");

        labelPresent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPresent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPresent.setText("Present : ");

        labelAbsent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelAbsent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelAbsent.setText("Absent : ");

        presentLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        presentLabel.setForeground(new java.awt.Color(51, 255, 0));
        presentLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        presentLabel.setText("------------");

        absentLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        absentLabel.setForeground(new java.awt.Color(255, 0, 0));
        absentLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        absentLabel.setText("-------------");

        checkBoxContact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkBoxContact.setText("Contact");
        checkBoxContact.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxContactItemStateChanged(evt);
            }
        });

        checkBoxAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkBoxAddress.setText("Address");
        checkBoxAddress.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxAddressItemStateChanged(evt);
            }
        });
        checkBoxAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAddressActionPerformed(evt);
            }
        });

        checkBoxState.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkBoxState.setText("State");
        checkBoxState.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxStateItemStateChanged(evt);
            }
        });
        checkBoxState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxStateActionPerformed(evt);
            }
        });

        checkBoxCity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkBoxCity.setText("City");
        checkBoxCity.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxCityItemStateChanged(evt);
            }
        });
        checkBoxCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxCityActionPerformed(evt);
            }
        });

        checkBoxRegID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkBoxRegID.setText("Unique Registration ID");
        checkBoxRegID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxRegIDItemStateChanged(evt);
            }
        });
        checkBoxRegID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxRegIDActionPerformed(evt);
            }
        });

        resetFiltersButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resetFiltersButton.setText("Reset Filters");
        resetFiltersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetFiltersButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelUserRegistration)
                .addGap(425, 425, 425)
                .addComponent(exitButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPresent)
                                    .addComponent(labelAbsent))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(absentLabel)
                                    .addComponent(presentLabel)))
                            .addComponent(checkBoxContact, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkBoxAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkBoxState, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkBoxCity, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkBoxRegID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetFiltersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateChooserFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFrom))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateChooserTo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSearch)
                            .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(labelUserRegistration))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exitButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFrom)
                    .addComponent(labelTo)
                    .addComponent(labelSearch)
                    .addComponent(labelPresent)
                    .addComponent(presentLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateChooserFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChooserTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelAbsent)
                                .addComponent(absentLabel)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(checkBoxContact)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxState)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxCity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxRegID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resetFiltersButton)))))
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void textSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSearchActionPerformed

    private void checkBoxAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxAddressActionPerformed

    private void checkBoxStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxStateActionPerformed

    private void checkBoxCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxCityActionPerformed

    private void checkBoxRegIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxRegIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxRegIDActionPerformed

    private void resetFiltersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetFiltersButtonActionPerformed
        // TODO add your handling code here:
        textSearch.setText("");
        dateChooserFrom.setDate(null);
        dateChooserTo.setDate(null);
        checkBoxContact.setSelected(false);
        checkBoxAddress.setSelected(false);
        checkBoxState.setSelected(false);
        checkBoxCity.setSelected(false);
        checkBoxRegID.setSelected(false);
        
        loadDataInTable();
    }//GEN-LAST:event_resetFiltersButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_formComponentShown

    private void checkBoxContactItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxContactItemStateChanged
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_checkBoxContactItemStateChanged

    private void checkBoxAddressItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxAddressItemStateChanged
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_checkBoxAddressItemStateChanged

    private void checkBoxStateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxStateItemStateChanged
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_checkBoxStateItemStateChanged

    private void checkBoxCityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxCityItemStateChanged
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_checkBoxCityItemStateChanged

    private void checkBoxRegIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxRegIDItemStateChanged
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_checkBoxRegIDItemStateChanged

    private void dateChooserFromPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooserFromPropertyChange
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_dateChooserFromPropertyChange

    private void dateChooserToPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooserToPropertyChange
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_dateChooserToPropertyChange

    private void textSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSearchKeyReleased
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_textSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewAttendance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel absentLabel;
    private javax.swing.JCheckBox checkBoxAddress;
    private javax.swing.JCheckBox checkBoxCity;
    private javax.swing.JCheckBox checkBoxContact;
    private javax.swing.JCheckBox checkBoxRegID;
    private javax.swing.JCheckBox checkBoxState;
    private com.toedter.calendar.JDateChooser dateChooserFrom;
    private com.toedter.calendar.JDateChooser dateChooserTo;
    private javax.swing.JButton exitButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAbsent;
    private javax.swing.JLabel labelFrom;
    private javax.swing.JLabel labelPresent;
    private javax.swing.JLabel labelSearch;
    private javax.swing.JLabel labelTo;
    private javax.swing.JLabel labelUserRegistration;
    private javax.swing.JLabel presentLabel;
    private javax.swing.JButton resetFiltersButton;
    private javax.swing.JTextField textSearch;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables

    private void loadDataInTable(){
        List<String> columns=new ArrayList<>(Arrays.asList(
                "ID", "Name", "Gender", "Email", "Date", "CheckIn", "CheckOut", "Work Duration"
        ));
        
        String searchText=textSearch.getText().toString();
        Date fromDateFromCal=dateChooserFrom.getDate();
        LocalDate fromDate=null;
        
        if(fromDateFromCal!=null)
        {
            fromDate=fromDateFromCal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }
        
        Date toDateFromCal=dateChooserTo.getDate();
        LocalDate toDate=null;
        
        if(toDateFromCal!=null)
        {
            toDate=toDateFromCal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }
        
        Long daysBetween=null;
        
        if(fromDate!=null && toDate!=null)
        {
            daysBetween=countWeekdays(fromDate, toDate);
        }
        
        Boolean contactIncluded=checkBoxContact.isSelected();
        Boolean addressIncluded=checkBoxAddress.isSelected();
        Boolean stateIncluded=checkBoxState.isSelected();
        Boolean cityIncluded=checkBoxCity.isSelected();
        Boolean regIDIncluded=checkBoxRegID.isSelected();
        
        String sqlQuery="SELECT ud.id, ud.name, ud.gender, ud.email, ua.date, ua.checkin, ua.checkout, ua.workduration";
        
        if(contactIncluded)
        {
            columns.add("Contact");
            sqlQuery+=", ud.contact";
        }
        
        if(addressIncluded)
        {
            columns.add("Address");
            sqlQuery+=", ud.address";
        }
        
        if(stateIncluded)
        {
            columns.add("State");
            sqlQuery+=", ud.state";
        }
        
        if(cityIncluded)
        {
            columns.add("City");
            sqlQuery+=", ud.city";
        }
        
        if(regIDIncluded)
        {
            columns.add("Reg ID");
            sqlQuery+=", ud.regid";
        }
        
        sqlQuery+=" FROM userdetails AS ud INNER JOIN userattendance AS ua ON ud.id=ua.userid ";
        
        if(searchText!=null && !searchText.isEmpty())
        {
            sqlQuery+="WHERE (ud.name like '%"+searchText+"%' OR ud.email like '%"+searchText+"%')";
            
            if(fromDate!=null && toDate!=null)
            {
                sqlQuery+=" AND ua.date BETWEEN '"+fromDate+"' AND '"+toDate+"'";
            }
            else if(fromDate!=null)
            {
                sqlQuery+=" AND ua.date = '"+fromDate+"'";
            }
        }
        else
        {
            if(fromDate!=null && toDate!=null)
            {
                sqlQuery+=" WHERE ua.date BETWEEN '"+fromDate+"' AND '"+toDate+"'";
            }
            else if(fromDate!=null)
            {
                sqlQuery+=" WHERE ua.date = '"+fromDate+"'";
            }
        }
        
        DefaultTableModel model=new DefaultTableModel();
        model.setColumnIdentifiers(columns.toArray());
        userTable.setModel(model);
        
        try
        {
            Connection c=ConnectionProvider.getConn();
            Statement statement=c.createStatement();
            ResultSet resultSet=statement.executeQuery(sqlQuery);
            Long presentCount=0L;
            Long absentCount=0L;
            Set<String> emailList=new HashSet<>();
            
            while(resultSet.next())
            {
                List<Object> row=new ArrayList<>();
                row.add(resultSet.getString("id"));
                row.add(resultSet.getString("name"));
                row.add(resultSet.getString("gender"));
                row.add(resultSet.getString("email"));
                emailList.add(resultSet.getString("email"));
                row.add(resultSet.getString("date"));
                row.add(resultSet.getString("checkin"));
                row.add(resultSet.getString("checkout"));
                row.add(resultSet.getString("workduration"));
                
                if(contactIncluded)
                {
                    row.add(resultSet.getString("contact"));
                }
                
                if(addressIncluded)
                {
                    row.add(resultSet.getString("address"));
                }
                
                if(stateIncluded)
                {
                    row.add(resultSet.getString("state"));
                }
                
                if(cityIncluded)
                {
                    row.add(resultSet.getString("city"));
                }
                
                if(regIDIncluded)
                {
                    row.add(resultSet.getString("regid"));
                }
                
                String checkoutValue=resultSet.getString("checkout");
                
                if(checkoutValue!=null && !checkoutValue.isEmpty())
                {
                    presentCount++;
                }
                else
                {
                    absentCount++;
                }
                
                model.addRow(row.toArray());
            }
            
            if(emailList.size()==1)
            {
                labelPresent.setVisible(true);
                labelAbsent.setVisible(true);
                presentLabel.setVisible(true);
                absentLabel.setVisible(true);
                presentLabel.setText(presentCount.toString());
                
                if(daysBetween!=null && daysBetween>0)
                {
                    absentCount=daysBetween-presentCount;
                }
                absentLabel.setText(absentCount.toString());
            }
            else
            {
                labelPresent.setVisible(false);
                labelAbsent.setVisible(false);
                presentLabel.setVisible(false);
                absentLabel.setVisible(false);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Something went wrong");
            e.printStackTrace();
        }
    }

    private Long countWeekdays(LocalDate start, LocalDate end){
        long count=0;
        LocalDate date=start;
         while(date.isBefore(end) || date.equals(end))
         {
             if(!(date.getDayOfWeek()==DayOfWeek.SATURDAY || date.getDayOfWeek()==DayOfWeek.SUNDAY))
             {
                 count++;
             }
             date=date.plusDays(1);
         }
         
         return count;
    }
}
